manifest = "6ad9af1796572f2312a6113e2454722ce621f1e8bf48547f4f0adb512e39830b"

[[dependency]]
package = "github.com/rainvg/drop"
target = "//:drop"

[lock."github.com/buckaroo-pm/jedisct1-libsodium"]
versions = [ "branch=master" ]
revision = "2841fd740122b966e6fa2cf8246f38a08f22caba"

[lock."github.com/rainvg/drop"]
versions = [ "branch=develop" ]
revision = "82eafcfc8b4563445f286105c69d71e511d14f94"
